[workspace]
members = [
    "crates/livestream-core",
    "crates/livestream-codec",
    "crates/livestream-transport",
    "crates/livestream-media",
    "crates/livestream-pipeline",
    "crates/livestream-telemetry",
]
resolver = "3"

[workspace.package]
version = "0.4.0"
edition = "2024"
license = "GPL-3.0"

[workspace.dependencies]
# core
tokio = { version = "1", default-features = false }
tokio-util = "0.7"
crossfire = "3"
serde = { version = "1", features = ["derive"] }
config = "0.15"
anyhow = "1"
async-trait = "0.1"

# codec / media
bytes = "1"
ffmpeg-sys-next = { version = "8", default-features = false }

# pipeline
tracing = "0.1"
parking_lot = "0.12"
tempfile = "3"

# transport
rml_rtmp = "0.8"
tonic = "0.14"
prost = "0.14"
axum = "0.8"
dashmap = "6"
tonic-prost-build = "0.14"
rtsp-types = "0.1"
tracing-subscriber = "0.3"

[package]
name = "livestream"
version.workspace = true
edition.workspace = true

[dependencies]
livestream-core = { path = "crates/livestream-core" }
livestream-codec = { path = "crates/livestream-codec" }
livestream-transport = { path = "crates/livestream-transport" }
livestream-media = { path = "crates/livestream-media" }
livestream-pipeline = { path = "crates/livestream-pipeline" }
livestream-telemetry = { path = "crates/livestream-telemetry" }
tokio = { workspace = true, features = ["rt-multi-thread"] }
anyhow.workspace = true

[build-dependencies]
tonic-prost-build.workspace = true
