[package]
name = "livestream-test-utils"
version.workspace = true
edition.workspace = true

[dependencies]
tokio = { workspace = true, features = ["full"] }
anyhow.workspace = true
serde.workspace = true
serde_json = "1"
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }
clap = { version = "4", features = ["derive"] }
tonic.workspace = true
tonic-prost.workspace = true
prost.workspace = true
tempfile.workspace = true

[build-dependencies]
tonic-prost-build.workspace = true
