[package]
name = "livestream-transport"
version.workspace = true
edition.workspace = true

[dependencies]
livestream-core = { path = "../livestream-core" }
livestream-codec = { path = "../livestream-codec" }
livestream-media = { path = "../livestream-media" }
livestream-pipeline = { path = "../livestream-pipeline" }
livestream-telemetry = { path = "../livestream-telemetry" }
tonic.workspace = true
tonic-prost.workspace = true
tonic-reflection = { workspace = true }
prost.workspace = true
axum.workspace = true
rtsp-types.workspace = true
base64.workspace = true
tokio = { workspace = true, features = ["full"] }
tokio-util.workspace = true
dashmap.workspace = true
tracing.workspace = true
anyhow.workspace = true
async-trait.workspace = true
bytes.workspace = true
rml_rtmp.workspace = true
crossfire.workspace = true
serde.workspace = true
parking_lot.workspace = true
config.workspace = true
async-stream = "0.3"
regex = "1"

[features]
opentelemetry = []

[build-dependencies]
tonic-prost-build.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
