services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SRT__PORTS: 4000-4100

      PERSISTENCE__DURATION: 10
      PERSISTENCE__CACHE_DIR:

      GRPC__PORT: 50051

      RTMP__PORT: 1935
      RTMP__APP_NAME: lives
      RTMP__SESSION_TTL_SECS: 30

      HTTP_FLV__ENABLED: true
      HTTP_FLV__PORT: 8080

      QUEUE__RTMP_FORWARD: 8192
      QUEUE__FLV_RELAY: 2048
      QUEUE__PACKET_RELAY: 2048
      QUEUE__CONTROL: 1024
      QUEUE__EVENT: 4096

      MINIO__URI: http://localhost:9000
      MINIO__ACCESS_KEY: minioadmin
      MINIO__SECRET_KEY: miniokey
      MINIO__BUCKET: videos

      RUST_LOG: info
    ports:
      - "50051:50051"
      - "1935:1935"
      - "4000-4100:4000-4100/udp"
    volumes:
      - ../..:/workspaces:cached
    networks:
      - devcontainer-net
    command: sleep infinity

  minio-service:
    image: minio/minio:latest
    container_name: minio-service
    # ports:
    #   - "9000:9000"
    #   - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: 123456MinIO
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    networks:
      - devcontainer-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-I", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  minio-data:

networks:
  devcontainer-net:
    driver: bridge
