//! Encoder — AVCodecContext RAII wrapper for the encode direction.
//!
//! Used by the `Transcode` processor (Phase 4).

use anyhow::Result;
use ffmpeg_sys_next::*;
use std::ffi::CString;
use std::os::raw::{c_char, c_int, c_void};

use crate::frame::Frame;
use crate::packet::Packet;

// ── FFmpeg compat declarations ──
// `av_opt_set` is not generated by the ffmpeg-sys-next 8.x bindings; declare
// it manually. The symbol is exported by libavutil, which is always linked.
unsafe extern "C" {
    fn av_opt_set(
        obj: *mut c_void,
        name: *const c_char,
        val: *const c_char,
        search_flags: c_int,
    ) -> c_int;
}

/// Wraps `AVCodecContext*` for encoding. Drop calls `avcodec_free_context`.
pub struct Encoder {
    ctx: *mut AVCodecContext,
}

// SAFETY: AVCodecContext is not thread-safe — must be wrapped in a Mutex
// when shared. The struct itself is `Send` for ownership transfer.
unsafe impl Send for Encoder {}

impl Encoder {
    /// Create a new encoder.
    ///
    /// Finds the encoder by codec ID, allocates a context, and configures
    /// basic encoding parameters.
    pub fn new(
        codec_id: AVCodecID,
        width: i32,
        height: i32,
        pix_fmt: AVPixelFormat,
        time_base: AVRational,
        bit_rate: i64,
        framerate: AVRational,
    ) -> Result<Self> {
        // SAFETY: avcodec_find_encoder returns a static descriptor or NULL.
        let codec = unsafe { avcodec_find_encoder(codec_id) };
        if codec.is_null() {
            anyhow::bail!("Encoder not found for codec ID: {:?}", codec_id);
        }
        Self::init(
            codec,
            width,
            height,
            pix_fmt,
            time_base,
            bit_rate,
            60,
            framerate,
            &[],
        )
    }

    /// Create a new encoder by codec name (e.g., `"libx264"`).
    ///
    /// Identical to [`Encoder::new`] except the codec is looked up by name;
    /// returns an error when no encoder with that name is available.
    pub fn new_named(
        codec_name: &str,
        width: i32,
        height: i32,
        pix_fmt: AVPixelFormat,
        time_base: AVRational,
        bit_rate: i64,
        framerate: AVRational,
    ) -> Result<Self> {
        Self::new_named_with_opts(
            codec_name,
            width,
            height,
            pix_fmt,
            time_base,
            bit_rate,
            60,
            framerate,
            &[],
        )
    }

    /// Create an encoder by name with pre-open tuning: GOP size, frame rate,
    /// and private options (e.g. libx264 `preset`/`tune`) are applied to the
    /// context **before** `avcodec_open2`.
    ///
    /// This matters: libx264 reads `gop_size`, `framerate`, and its private
    /// options once during open — setting them afterwards (see
    /// [`Encoder::set_gop_size`], [`Encoder::apply_private_option`]) has no
    /// effect on the running encoder. Private options unknown to the encoder
    /// are logged at debug level and skipped; they never fail construction.
    #[allow(clippy::too_many_arguments)]
    pub fn new_named_with_opts(
        codec_name: &str,
        width: i32,
        height: i32,
        pix_fmt: AVPixelFormat,
        time_base: AVRational,
        bit_rate: i64,
        gop_size: i32,
        framerate: AVRational,
        options: &[(&str, &str)],
    ) -> Result<Self> {
        let c_name = CString::new(codec_name)?;
        // SAFETY: avcodec_find_encoder_by_name returns a static descriptor or NULL.
        let codec = unsafe { avcodec_find_encoder_by_name(c_name.as_ptr()) };
        if codec.is_null() {
            anyhow::bail!("Encoder not found by name: {}", codec_name);
        }
        Self::init(
            codec, width, height, pix_fmt, time_base, bit_rate, gop_size, framerate, options,
        )
    }

    /// Allocate, configure, and open a context for an already-looked-up codec.
    #[allow(clippy::too_many_arguments)]
    fn init(
        codec: *const AVCodec,
        width: i32,
        height: i32,
        pix_fmt: AVPixelFormat,
        time_base: AVRational,
        bit_rate: i64,
        gop_size: i32,
        framerate: AVRational,
        options: &[(&str, &str)],
    ) -> Result<Self> {
        // SAFETY: avcodec_alloc_context3 returns a heap-allocated context or NULL.
        let mut ctx = unsafe { avcodec_alloc_context3(codec) };
        if ctx.is_null() {
            anyhow::bail!("Failed to allocate encoder context");
        }

        // SAFETY: ctx is a freshly allocated AVCodecContext. Setting fields
        // before opening is the standard FFmpeg pattern.
        unsafe {
            (*ctx).width = width;
            (*ctx).height = height;
            (*ctx).pix_fmt = pix_fmt;
            (*ctx).time_base = time_base;
            (*ctx).framerate = framerate;
            (*ctx).bit_rate = bit_rate;
            (*ctx).gop_size = gop_size;
            (*ctx).max_b_frames = 0;
        }

        // Private options must be set before avcodec_open2 — libx264 reads
        // them in its init.
        for (key, value) in options {
            let c_key = CString::new(*key)?;
            let c_value = CString::new(*value)?;
            // SAFETY: priv_data is the encoder's private-option context;
            // av_opt_set is the standard API for setting options on it.
            let ret = unsafe { av_opt_set((*ctx).priv_data, c_key.as_ptr(), c_value.as_ptr(), 0) };
            if ret < 0 {
                tracing::debug!(
                    key = *key,
                    value = *value,
                    error = crate::ffmpeg_error(ret),
                    "encoder private option not applied"
                );
            }
        }

        // SAFETY: Context is configured; avcodec_open2 initializes the encoder.
        let ret = unsafe { avcodec_open2(ctx, std::ptr::null(), std::ptr::null_mut()) };
        if ret < 0 {
            // SAFETY: Free context on failure before returning error.
            unsafe {
                avcodec_free_context(&mut ctx);
            }
            anyhow::bail!("Failed to open encoder: {}", crate::ffmpeg_error(ret));
        }

        Ok(Self { ctx })
    }

    /// Set the GOP size in frames (keyframe interval target).
    pub fn set_gop_size(&mut self, frames: i32) {
        // SAFETY: reading/writing a field of a valid AVCodecContext pointer.
        unsafe {
            (*self.ctx).gop_size = frames;
        }
    }

    /// Set the maximum number of B-frames between reference frames.
    pub fn set_max_b_frames(&mut self, n: i32) {
        // SAFETY: reading/writing a field of a valid AVCodecContext pointer.
        unsafe {
            (*self.ctx).max_b_frames = n;
        }
    }

    /// Set a private encoder option (e.g., libx264 `preset`).
    ///
    /// Returns an error when the encoder has no such private option — callers
    /// targeting non-libx264 fallback encoders should tolerate that.
    pub fn apply_private_option(&mut self, key: &str, value: &str) -> Result<()> {
        let c_key = CString::new(key)?;
        let c_value = CString::new(value)?;
        // SAFETY: priv_data is the encoder's private-option context; av_opt_set
        // is the standard API for setting options on it. The strings are valid
        // NUL-terminated C strings for the duration of the call.
        let ret = unsafe { av_opt_set((*self.ctx).priv_data, c_key.as_ptr(), c_value.as_ptr(), 0) };
        if ret < 0 {
            anyhow::bail!(
                "Failed to set encoder option {}={}: {}",
                key,
                value,
                crate::ffmpeg_error(ret)
            );
        }
        Ok(())
    }

    /// Send a raw frame to the encoder.
    ///
    /// Pass `None` to flush the encoder (drain remaining packets).
    pub fn send_frame(&mut self, frame: Option<&Frame>) -> Result<()> {
        let frame_ptr = frame.map(|f| f.as_ptr()).unwrap_or(std::ptr::null());
        // SAFETY: frame_ptr is either a valid AVFrame pointer or NULL (flush).
        let ret = unsafe { avcodec_send_frame(self.ctx, frame_ptr) };
        if ret < 0 {
            anyhow::bail!(
                "Failed to send frame to encoder: {}",
                crate::ffmpeg_error(ret)
            );
        }
        Ok(())
    }

    /// Receive an encoded packet from the encoder.
    ///
    /// Returns `Ok(true)` when a packet is available, `Ok(false)` when more
    /// frames are needed (`AVERROR(EAGAIN)`) or the stream ended (`AVERROR_EOF`),
    /// and `Err` on fatal errors.
    pub fn receive_packet(&mut self, pkt: &mut Packet) -> Result<bool> {
        // SAFETY: Both pointers are valid. avcodec_receive_packet fills
        // the packet with encoded data.
        let ret = unsafe { avcodec_receive_packet(self.ctx, pkt.as_mut_ptr()) };
        if ret == AVERROR(EAGAIN) || ret == AVERROR_EOF {
            return Ok(false);
        }
        if ret < 0 {
            anyhow::bail!(
                "Failed to receive packet from encoder: {}",
                crate::ffmpeg_error(ret)
            );
        }
        Ok(true)
    }

    /// Get the encoder's time base.
    pub fn time_base(&self) -> AVRational {
        // SAFETY: reading field from valid AVCodecContext pointer.
        unsafe { (*self.ctx).time_base }
    }

    /// Get the frame rate the encoder was opened with.
    pub fn framerate(&self) -> AVRational {
        // SAFETY: reading field from valid AVCodecContext pointer.
        unsafe { (*self.ctx).framerate }
    }

    /// Get the encoder's pixel format.
    pub fn pixel_format(&self) -> AVPixelFormat {
        // SAFETY: reading field from valid AVCodecContext pointer.
        unsafe { (*self.ctx).pix_fmt }
    }

    pub fn width(&self) -> i32 {
        // SAFETY: reading field from valid AVCodecContext pointer.
        unsafe { (*self.ctx).width }
    }

    pub fn height(&self) -> i32 {
        // SAFETY: reading field from valid AVCodecContext pointer.
        unsafe { (*self.ctx).height }
    }
}

impl Drop for Encoder {
    fn drop(&mut self) {
        // SAFETY: avcodec_free_context frees the context and NULLs the pointer.
        unsafe {
            avcodec_free_context(&mut self.ctx);
        }
    }
}

// ── Tests ──

#[cfg(test)]
mod tests {
    use super::*;
    use ffmpeg_sys_next::AVPixelFormat;

    #[test]
    fn create_h264_encoder() {
        let enc = Encoder::new(
            AVCodecID::AV_CODEC_ID_H264,
            1920,
            1080,
            AVPixelFormat::AV_PIX_FMT_YUV420P,
            AVRational { num: 1, den: 30 },
            2_000_000,
            AVRational { num: 30, den: 1 },
        );
        assert!(enc.is_ok());
    }

    #[test]
    fn encoder_has_correct_params() {
        let enc = Encoder::new(
            AVCodecID::AV_CODEC_ID_H264,
            1280,
            720,
            AVPixelFormat::AV_PIX_FMT_YUV420P,
            AVRational { num: 1, den: 25 },
            1_000_000,
            AVRational { num: 25, den: 1 },
        )
        .unwrap();
        assert_eq!(enc.width(), 1280);
        assert_eq!(enc.height(), 720);
        assert_eq!(enc.pixel_format(), AVPixelFormat::AV_PIX_FMT_YUV420P);
        assert_eq!(enc.time_base().num, 1);
        assert_eq!(enc.time_base().den, 25);
        assert_eq!(enc.framerate().num, 25);
        assert_eq!(enc.framerate().den, 1);
    }

    #[test]
    fn create_named_encoder() {
        // libx264 may be absent on minimal systems — only assert success
        // when the encoder is available.
        match Encoder::new_named(
            "libx264",
            320,
            240,
            AVPixelFormat::AV_PIX_FMT_YUV420P,
            AVRational { num: 1, den: 1000 },
            1_000_000,
            AVRational { num: 30, den: 1 },
        ) {
            Ok(_) => {}
            Err(e) => {
                let msg = format!("{:#}", e);
                if msg.contains("not found") {
                    eprintln!("libx264 not available, skipping");
                } else {
                    panic!("unexpected encoder error: {}", msg);
                }
            }
        }
    }

    #[test]
    fn encoder_private_options() {
        let mut enc = Encoder::new(
            AVCodecID::AV_CODEC_ID_H264,
            320,
            240,
            AVPixelFormat::AV_PIX_FMT_YUV420P,
            AVRational { num: 1, den: 1000 },
            1_000_000,
            AVRational { num: 30, den: 1 },
        )
        .unwrap();
        enc.set_gop_size(30);
        enc.set_max_b_frames(0);
        // "preset" is a libx264-only private option; on encoders without it
        // (e.g. the native h264 fallback) the error is expected — tolerate it.
        if let Err(e) = enc.apply_private_option("preset", "veryfast") {
            eprintln!("preset option unavailable: {}", e);
        }
    }
}
